import os
from dotenv import load_dotenv
load_dotenv()

PIPEDRIVE_API_KEY = os.getenv("PIPEDRIVE_API_KEY")
# deals
LOAN_AMOUNT_KEY = os.getenv("LOAN_AMOUNT_KEY")
VALUE_KEY = os.getenv("VALUE_KEY")
EXPECTED_CLOSE_DATE_KEY=os.getenv("EXPECTED_CLOSE_DATE_KEY")
SELF_SOURCED_KEY=os.getenv("SELF_SOURCED_KEY")
FIRST_PAYMENT_DATE_KEY=os.getenv("FIRST_PAYMENT_DATE_KEY")
TWOHUNDREDTEN_DAYS_KEY=os.getenv("TWOHUNDREDTEN_DAYS_KEY")
COMMISSION_KEY=os.getenv("COMMISSION_KEY")
COBORROWER_KEY=os.getenv("COBORROWER_KEY")
BUYER_AGENT_KEY=os.getenv("BUYER_AGENT_KEY")
LISTING_AGENT_KEY=os.getenv("LISTING_AGENT_KEY")
FUNDED_DATE_KEY=os.getenv("FUNDED_DATE_KEY")
BRANCH_PRICING_KEY=os.getenv("BRANCH_PRICING_KEY")
COMPANY_LEAD_KEY=os.getenv("COMPANY_LEAD_KEY")
LOAN_NUMBER_KEY=os.getenv("LOAN_NUMBER_KEY")
DEAL_TITLE_KEY=os.getenv("DEAL_TITLE_KEY")
BUY_SIDES_KEY=os.getenv("BUY_SIDES_KEY")
BUY_VOLUME_KEY=os.getenv("BUY_VOLUME_KEY")
AVERAGE_BUY_VOLUME_KEY=os.getenv("AVERAGE_BUY_VOLUME_KEY")
# contacts
CONTACT_LABEL_KEY=os.getenv("CONTACT_LABEL_KEY")
BIRTHDAY_KEY=os.getenv("BIRTHDAY_KEY")
BIRTH_MONTH_KEY=os.getenv("BIRTH_MONTH_KEY")
# pipeline
APPLICATION_IN_STAGE_ID=int(os.getenv("APPLICATION_IN_STAGE_ID", "0"))
PREAPPROVED_STAGE_ID=int(os.getenv("PREAPPROVED_STAGE_ID", "0"))
GETTING_THINGS_ROLLING_STAGE_ID=int(os.getenv("GETTING_THINGS_ROLLING_STAGE_ID", "0"))
IN_PROCESS_STAGE_ID=int(os.getenv("IN_PROCESS_STAGE_ID", "0"))
CLEAR_TO_CLOSE_STAGE_ID=int(os.getenv("CLEAR_TO_CLOSE_STAGE_ID", "0"))
# status
WON_STATUS=os.getenv("WON_STATUS")
LOST_STATUS=os.getenv("LOST_STATUS")