import os
from dotenv import load_dotenv
load_dotenv()

PIPEDRIVE_API_KEY = os.getenv("PIPEDRIVE_API_KEY")
# deals
LOAN_AMOUNT_KEY = os.getenv("LOAN_AMOUNT_KEY")
VALUE_KEY = os.getenv("VALUE_KEY")
EXPECTED_CLOSE_DATE_KEY=os.getenv("EXPECTED_CLOSE_DATE_KEY")
SELF_SOURCED_KEY=os.getenv("SELF_SOURCED_KEY")
FIRST_PAYMENT_DATE_KEY=os.getenv("FIRST_PAYMENT_DATE_KEY")
TWOHUNDREDTEN_DAYS_KEY=os.getenv("TWOHUNDREDTEN_DAYS_KEY")
COMMISSION_KEY=os.getenv("COMMISSION_KEY")
COBORROWER_KEY=os.getenv("COBORROWER_KEY")
BUYER_AGENT_KEY=os.getenv("BUYER_AGENT_KEY")
LISTING_AGENT_KEY=os.getenv("LISTING_AGENT_KEY")
FUNDED_DATE_KEY=os.getenv("FUNDED_DATE_KEY")
BRANCH_PRICING_KEY=os.getenv("BRANCH_PRICING_KEY")
COMPANY_LEAD_KEY=os.getenv("COMPANY_LEAD_KEY")
LOAN_NUMBER_KEY=os.getenv("LOAN_NUMBER_KEY")
DEAL_TITLE_KEY=os.getenv("DEAL_TITLE_KEY")
BUY_SIDES_KEY=os.getenv("BUY_SIDES_KEY")
BUY_VOLUME_KEY=os.getenv("BUY_VOLUME_KEY")
AVERAGE_BUY_VOLUME_KEY=os.getenv("AVERAGE_BUY_VOLUME_KEY")
# contacts
CONTACT_LABEL_KEY=os.getenv("CONTACT_LABEL_KEY")
BIRTHDAY_KEY=os.getenv("BIRTHDAY_KEY")
BIRTH_MONTH_KEY=os.getenv("BIRTH_MONTH_KEY")
# pipeline
APPLICATION_IN_STAGE_ID=int(os.getenv("APPLICATION_IN_STAGE_ID", "0"))
PREAPPROVED_STAGE_ID=int(os.getenv("PREAPPROVED_STAGE_ID", "0"))
GETTING_THINGS_ROLLING_STAGE_ID=int(os.getenv("GETTING_THINGS_ROLLING_STAGE_ID", "0"))
IN_PROCESS_STAGE_ID=int(os.getenv("IN_PROCESS_STAGE_ID", "0"))
CLEAR_TO_CLOSE_STAGE_ID=int(os.getenv("CLEAR_TO_CLOSE_STAGE_ID", "0"))
# status
WON_STATUS=os.getenv("WON_STATUS")
LOST_STATUS=os.getenv("LOST_STATUS")

# Salesforce sync - custom field keys for storing Salesforce IDs
PIPEDRIVE_SALESFORCE_LOAN_ID_KEY=os.getenv("PIPEDRIVE_SALESFORCE_LOAN_ID_KEY")
PIPEDRIVE_SALESFORCE_CONTACT_ID_KEY=os.getenv("PIPEDRIVE_SALESFORCE_CONTACT_ID_KEY")

# New Deal Field Keys (Salesforce sync)
BASE_LOAN_AMOUNT_KEY=os.getenv("BASE_LOAN_AMOUNT_KEY")
PRE_APPROVAL_SENT_DATE_KEY=os.getenv("PRE_APPROVAL_SENT_DATE_KEY")
STRATEGY_CALL_KEY=os.getenv("STRATEGY_CALL_KEY")
LOAN_PAID_OFF_KEY=os.getenv("LOAN_PAID_OFF_KEY")
PROPERTY_TYPE_KEY=os.getenv("PROPERTY_TYPE_KEY")
PROPERTY_ADDRESS_KEY=os.getenv("PROPERTY_ADDRESS_KEY")
LOAN_TYPE_KEY=os.getenv("LOAN_TYPE_KEY")
LOAN_PURPOSE_KEY=os.getenv("LOAN_PURPOSE_KEY")
OCCUPANCY_KEY=os.getenv("OCCUPANCY_KEY")
APPRAISED_VALUE_KEY=os.getenv("APPRAISED_VALUE_KEY")
PURCHASE_PRICE_KEY=os.getenv("PURCHASE_PRICE_KEY")
DOWN_PAYMENT_KEY=os.getenv("DOWN_PAYMENT_KEY")
INTEREST_RATE_KEY=os.getenv("INTEREST_RATE_KEY")
TERM_KEY=os.getenv("TERM_KEY")
FUNDING_FEE_KEY=os.getenv("FUNDING_FEE_KEY")
CREDIT_SCORE_KEY=os.getenv("CREDIT_SCORE_KEY")
LOAN_PROGRAM_KEY=os.getenv("LOAN_PROGRAM_KEY")
MONTHLY_PAYMENT_KEY=os.getenv("MONTHLY_PAYMENT_KEY")
HOMEOWNERS_INSURANCE_KEY=os.getenv("HOMEOWNERS_INSURANCE_KEY")
PROPERTY_TAX_KEY=os.getenv("PROPERTY_TAX_KEY")
MORTGAGE_INSURANCE_KEY=os.getenv("MORTGAGE_INSURANCE_KEY")
HOA_KEY=os.getenv("HOA_KEY")
SUPPLEMENTAL_PROPERTY_INSURANCE_KEY=os.getenv("SUPPLEMENTAL_PROPERTY_INSURANCE_KEY")
B1_ANNUAL_INCOME_KEY=os.getenv("B1_ANNUAL_INCOME_KEY")
B2_ANNUAL_INCOME_KEY=os.getenv("B2_ANNUAL_INCOME_KEY")
COBORROWER_NAME_KEY=os.getenv("COBORROWER_NAME_KEY")
PI_PAYMENT_KEY=os.getenv("PI_PAYMENT_KEY")

# Important Dates
ECONSENT_KEY=os.getenv("ECONSENT_KEY")
LE_DUE_KEY=os.getenv("LE_DUE_KEY")
LE_SENT_KEY=os.getenv("LE_SENT_KEY")
LE_RECEIVED_KEY=os.getenv("LE_RECEIVED_KEY")
APPRAISAL_ORDERED_KEY=os.getenv("APPRAISAL_ORDERED_KEY")
APPRAISAL_RECEIVED_KEY=os.getenv("APPRAISAL_RECEIVED_KEY")
TITLE_RECEIVED_KEY=os.getenv("TITLE_RECEIVED_KEY")
INSURANCE_RECEIVED_KEY=os.getenv("INSURANCE_RECEIVED_KEY")
CD_SENT_KEY=os.getenv("CD_SENT_KEY")
CD_RECEIVED_KEY=os.getenv("CD_RECEIVED_KEY")

# Person Fields
GROUP_KEY=os.getenv("GROUP_KEY")
CONTACT_TYPE_KEY=os.getenv("CONTACT_TYPE_KEY")
CONTACT_GROUP_KEY=os.getenv("CONTACT_GROUP_KEY")

# Group Option IDs (for updating Group field)
LEAD_GROUP_ID=int(os.getenv("LEAD_GROUP_ID", "0"))
BORROWER_GROUP_ID=int(os.getenv("BORROWER_GROUP_ID", "0"))

# Occupancy Option IDs
PRIMARY_OCCUPANCY_ID=int(os.getenv("PRIMARY_OCCUPANCY_ID", "0"))
SECOND_HOME_OCCUPANCY_ID=int(os.getenv("SECOND_HOME_OCCUPANCY_ID", "0"))
INVESTMENT_OCCUPANCY_ID=int(os.getenv("INVESTMENT_OCCUPANCY_ID", "0"))

# Contact Type Option IDs
CONTACT_TYPE_CLIENT_ID=int(os.getenv("CONTACT_TYPE_CLIENT_ID", "88"))
CONTACT_TYPE_BUSINESS_ID=int(os.getenv("CONTACT_TYPE_BUSINESS_ID", "89"))

# Down Payment % field key
DOWN_PAYMENT_PERCENT_KEY=os.getenv("DOWN_PAYMENT_PERCENT_KEY")

# Deal Labels
DEAL_LABEL_FIELD_KEY=os.getenv("DEAL_LABEL_FIELD_KEY", "label")
LABEL_APPLICATION_ID=int(os.getenv("LABEL_APPLICATION_ID", "0"))
LABEL_PRE_APPROVED_ID=int(os.getenv("LABEL_PRE_APPROVED_ID", "0"))
LABEL_GETTING_THINGS_ROLLING_ID=int(os.getenv("LABEL_GETTING_THINGS_ROLLING_ID", "0"))
LABEL_IN_PROCESS_ID=int(os.getenv("LABEL_IN_PROCESS_ID", "0"))
LABEL_SUBMITTED_ID=int(os.getenv("LABEL_SUBMITTED_ID", "0"))
LABEL_COND_APPROVAL_ID=int(os.getenv("LABEL_COND_APPROVAL_ID", "0"))
LABEL_APPROVED_ID=int(os.getenv("LABEL_APPROVED_ID", "0"))
LABEL_CLEAR_TO_CLOSE_ID=int(os.getenv("LABEL_CLEAR_TO_CLOSE_ID", "0"))
LABEL_DOCS_OUT_ID=int(os.getenv("LABEL_DOCS_OUT_ID", "0"))
LABEL_CLOSED_ID=int(os.getenv("LABEL_CLOSED_ID", "0"))
LABEL_SUSPENDED_ID=int(os.getenv("LABEL_SUSPENDED_ID", "0"))
LABEL_CANCELLED_ID=int(os.getenv("LABEL_CANCELLED_ID", "0"))